[package]
name = "event-queue-demo"
version = "0.1.0"
authors = ["Kenny Foner <kwf@galois.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]

[dev-dependencies]
quickcheck = "0.9"